/* Querrys Rezepte*/
SELECT ZUTAT.ZUTATENNR,
       ZUTAT.BEZEICHNUNG,
       REZEPTZUTATEN.MENGE,
       REZEPTZUTATEN.EINHEIT

    FROM((ZUTAT
        INNER JOIN REZEPTZUTATEN
                ON ZUTAT.ZUTATENNR =
                    REZEPTZUTATEN.ZUTATENNR)
            INNER JOIN REZEPTE
                    ON REZEPTZUTATEN.REZEPTNR =
                        REZEPTE.REZEPTNR)
WHERE REZEPT='Lachslasagne';

SELECT ZUTAT.ZUTATENNR,
       ZUTAT.BEZEICHNUNG,
       REZEPTZUTATEN.MENGE,
       REZEPTZUTATEN.EINHEIT

    FROM((ZUTAT
        INNER JOIN REZEPTZUTATEN
                ON ZUTAT.ZUTATENNR =
                    REZEPTZUTATEN.ZUTATENNR)
            INNER JOIN REZEPTE
                    ON REZEPTZUTATEN.REZEPTNR =
                        REZEPTE.REZEPTNR)
WHERE REZEPT='Thaicurry mit Hähnchen';

SELECT ZUTAT.ZUTATENNR,
       ZUTAT.BEZEICHNUNG,
       REZEPTZUTATEN.MENGE,
       REZEPTZUTATEN.EINHEIT

    FROM((ZUTAT
        INNER JOIN REZEPTZUTATEN
                ON ZUTAT.ZUTATENNR =
                    REZEPTZUTATEN.ZUTATENNR)
            INNER JOIN REZEPTE
                    ON REZEPTZUTATEN.REZEPTNR =
                        REZEPTE.REZEPTNR)
WHERE REZEPT='Kartoffelsuppe';

SELECT ZUTAT.ZUTATENNR,
       ZUTAT.BEZEICHNUNG,
       REZEPTZUTATEN.MENGE,
       REZEPTZUTATEN.EINHEIT

    FROM((ZUTAT
        INNER JOIN REZEPTZUTATEN
                ON ZUTAT.ZUTATENNR =
                    REZEPTZUTATEN.ZUTATENNR)
            INNER JOIN REZEPTE
                    ON REZEPTZUTATEN.REZEPTNR =
                        REZEPTE.REZEPTNR)
WHERE REZEPT='Milchreis mit Apfelmus';

SELECT ZUTAT.ZUTATENNR,
       ZUTAT.BEZEICHNUNG,
       REZEPTZUTATEN.MENGE,
       REZEPTZUTATEN.EINHEIT

    FROM((ZUTAT
        INNER JOIN REZEPTZUTATEN
                ON ZUTAT.ZUTATENNR =
                    REZEPTZUTATEN.ZUTATENNR)
            INNER JOIN REZEPTE
                    ON REZEPTZUTATEN.REZEPTNR =
                        REZEPTE.REZEPTNR)
WHERE REZEPT='Sommerlicher Couscous-Salat';




/* Querrys Ernährungskategorien*/
SELECT REZEPTKATEGORIEN.REZEPTNR,
       REZEPTE.REZEPT,
       REZEPTKATEGORIEN.KATEGORIENR,
       ERNAEHRUNGSKATEGORIEN.KATEGORIE

    FROM((REZEPTE
        LEFT JOIN REZEPTKATEGORIEN
                ON REZEPTE.REZEPTNR =
                    REZEPTKATEGORIEN.REZEPTNR)
        RIGHT JOIN ERNAEHRUNGSKATEGORIEN
                ON REZEPTKATEGORIEN.KATEGORIENR =
                    ERNAEHRUNGSKATEGORIEN.KATEGORIENR)
WHERE KATEGORIE='Vegan';

SELECT REZEPTKATEGORIEN.REZEPTNR,
       REZEPTE.REZEPT,
       REZEPTKATEGORIEN.KATEGORIENR,
       ERNAEHRUNGSKATEGORIEN.KATEGORIE

    FROM((REZEPTE
        LEFT JOIN REZEPTKATEGORIEN
                ON REZEPTE.REZEPTNR =
                    REZEPTKATEGORIEN.REZEPTNR)
        RIGHT JOIN ERNAEHRUNGSKATEGORIEN
                ON REZEPTKATEGORIEN.KATEGORIENR =
                    ERNAEHRUNGSKATEGORIEN.KATEGORIENR)
WHERE KATEGORIE='Vegetarisch';

SELECT REZEPTKATEGORIEN.REZEPTNR,
       REZEPTE.REZEPT,
       REZEPTKATEGORIEN.KATEGORIENR,
       ERNAEHRUNGSKATEGORIEN.KATEGORIE

    FROM((REZEPTE
        LEFT JOIN REZEPTKATEGORIEN
                ON REZEPTE.REZEPTNR =
                    REZEPTKATEGORIEN.REZEPTNR)
        RIGHT JOIN ERNAEHRUNGSKATEGORIEN 
                ON REZEPTKATEGORIEN.KATEGORIENR =
                    ERNAEHRUNGSKATEGORIEN.KATEGORIENR)
WHERE KATEGORIE='Frutarisch';

SELECT REZEPTKATEGORIEN.REZEPTNR,
       REZEPTE.REZEPT,
       REZEPTKATEGORIEN.KATEGORIENR,
       ERNAEHRUNGSKATEGORIEN.KATEGORIE

    FROM((REZEPTE
        LEFT JOIN REZEPTKATEGORIEN
                ON REZEPTE.REZEPTNR =
                    REZEPTKATEGORIEN.REZEPTNR)
        RIGHT JOIN ERNAEHRUNGSKATEGORIEN
                ON REZEPTKATEGORIEN.KATEGORIENR =
                    ERNAEHRUNGSKATEGORIEN.KATEGORIENR)
WHERE KATEGORIE='Laktosefrei';

SELECT REZEPTKATEGORIEN.REZEPTNR,
       REZEPTE.REZEPT,
       REZEPTKATEGORIEN.KATEGORIENR,
       ERNAEHRUNGSKATEGORIEN.KATEGORIE

    FROM((REZEPTE
        LEFT JOIN REZEPTKATEGORIEN
                ON REZEPTE.REZEPTNR =
                    REZEPTKATEGORIEN.REZEPTNR)
        RIGHT JOIN ERNAEHRUNGSKATEGORIEN
                ON REZEPTKATEGORIEN.KATEGORIENR =
                    ERNAEHRUNGSKATEGORIEN.KATEGORIENR)
WHERE KATEGORIE='Glutenfrei';

SELECT REZEPTKATEGORIEN.REZEPTNR,
       REZEPTE.REZEPT,
       REZEPTKATEGORIEN.KATEGORIENR,
       ERNAEHRUNGSKATEGORIEN.KATEGORIE

    FROM((REZEPTE
        LEFT JOIN REZEPTKATEGORIEN
                ON REZEPTE.REZEPTNR =
                    REZEPTKATEGORIEN.REZEPTNR)
        RIGHT JOIN ERNAEHRUNGSKATEGORIEN
                ON REZEPTKATEGORIEN.KATEGORIENR =
                    ERNAEHRUNGSKATEGORIEN.KATEGORIENR)
WHERE KATEGORIE='Low Carb';




/* Querrys Allergien*/
SELECT REZEPTE.REZEPTNR,
       REZEPTE.REZEPT,
       ALLERGENE.ALLERGIENNR,
       ALLERGENE.ALLERGIEN

    FROM((REZEPTE
        INNER JOIN REZEPTALERGENE
                ON REZEPTE.REZEPTNR =
                    REZEPTALERGENE.REZEPTNR)
        INNER JOIN ALLERGENE
                ON REZEPTALERGENE.ALLERGIENNR =
                    ALLERGENE.ALLERGIENNR)
WHERE ALLERGIEN !='Laktose';

SELECT REZEPTE.REZEPTNR,
       REZEPTE.REZEPT,
       ALLERGENE.ALLERGIENNR,
       ALLERGENE.ALLERGIEN

    FROM((REZEPTE
        INNER JOIN REZEPTALERGENE
                ON REZEPTE.REZEPTNR =
                    REZEPTALERGENE.REZEPTNR)
        INNER JOIN ALLERGENE
                ON REZEPTALERGENE.ALLERGIENNR =
                    ALLERGENE.ALLERGIENNR)
WHERE ALLERGIEN !='Weizen';

SELECT REZEPTE.REZEPTNR,
       REZEPTE.REZEPT,
       ALLERGENE.ALLERGIENNR,
       ALLERGENE.ALLERGIEN

    FROM((REZEPTE
        INNER JOIN REZEPTALERGENE
                ON REZEPTE.REZEPTNR =
                    REZEPTALERGENE.REZEPTNR)
        INNER JOIN ALLERGENE
                ON REZEPTALERGENE.ALLERGIENNR =
                    ALLERGENE.ALLERGIENNR)
WHERE ALLERGIEN !='Gluten';

SELECT REZEPTE.REZEPTNR,
       REZEPTE.REZEPT,
       ALLERGENE.ALLERGIENNR,
       ALLERGENE.ALLERGIEN

    FROM((REZEPTE
        INNER JOIN REZEPTALERGENE
                ON REZEPTE.REZEPTNR =
                    REZEPTALERGENE.REZEPTNR)
        INNER JOIN ALLERGENE
                ON REZEPTALERGENE.ALLERGIENNR =
                    ALLERGENE.ALLERGIENNR)
WHERE ALLERGIEN !='Stärke';

SELECT REZEPTE.REZEPTNR,
       REZEPTE.REZEPT,
       ALLERGENE.ALLERGIENNR,
       ALLERGENE.ALLERGIEN

    FROM((REZEPTE
        INNER JOIN REZEPTALERGENE
                ON REZEPTE.REZEPTNR =
                    REZEPTALERGENE.REZEPTNR)
        INNER JOIN ALLERGENE
                ON REZEPTALERGENE.ALLERGIENNR =
                    ALLERGENE.ALLERGIENNR)
WHERE ALLERGIEN !='Karrotten';




/*Querry Rezepte Ohne Zutaten*/
SELECT * FROM REZEPTE
    WHERE REZEPT='Lachslasagne';

SELECT * FROM REZEPTE
    WHERE REZEPT='Thaicurry mit Hähnchen';

SELECT * FROM REZEPTE
    WHERE REZEPT='Kartoffelsuppe';

SELECT * FROM REZEPTE
    WHERE REZEPT='Milchreis mit Apfelmus';

SELECT * FROM REZEPTE
    WHERE REZEPT='Sommerlicher Couscous-Salat';



/*Nicht in Rezepten genutzt */
SELECT ZUTAT.ZUTATENNR, ZUTAT.BEZEICHNUNG FROM ZUTAT
    LEFT JOIN REZEPTZUTATEN
        ON REZEPTZUTATEN.ZUTATENNR = ZUTAT.ZUTATENNR
WHERE REZEPTZUTATEN.ZUTATENNR IS NULL;




/*Rezepte mit einer Zutat nach wahl*/
SELECT REZEPTZUTATEN.REZEPTNR,
       REZEPTE.REZEPT,
       REZEPTZUTATEN.ZUTATENNR,
       REZEPTZUTATEN.MENGE,
       REZEPTZUTATEN.EINHEIT,
       ZUTAT.BEZEICHNUNG

    FROM((REZEPTE
        INNER JOIN REZEPTZUTATEN
                ON REZEPTE.REZEPTNR =
                    REZEPTZUTATEN.REZEPTNR)
        INNER JOIN ZUTAT
                ON REZEPTZUTATEN.ZUTATENNR =
                    ZUTAT.ZUTATENNR)
WHERE BEZEICHNUNG='Pfeffer';

SELECT REZEPTZUTATEN.REZEPTNR,
       REZEPTE.REZEPT,
       REZEPTZUTATEN.ZUTATENNR,
       REZEPTZUTATEN.MENGE,
       REZEPTZUTATEN.EINHEIT,
       ZUTAT.BEZEICHNUNG

    FROM((REZEPTE
        INNER JOIN REZEPTZUTATEN 
                ON REZEPTE.REZEPTNR = 
                    REZEPTZUTATEN.REZEPTNR)
        INNER JOIN ZUTAT 
                ON REZEPTZUTATEN.ZUTATENNR = 
                    ZUTAT.ZUTATENNR)
WHERE BEZEICHNUNG='Tomate';




/*Alle bestellunge von Kunde X*/
SELECT KUNDENNR, NACHNAME, BESTELLNR, BESTELLDATUM
    FROM KUNDE
    LEFT JOIN BESTELLUNG
        ON KUNDE.KUNDENNR =
            BESTELLUNG.KUNDENNR
WHERE KUNDE.KUNDENNR=2001;




/*AVG einer Bestllung*/
SELECT KUNDE.KUNDENNR, 
       KUNDE.NACHNAME,
    ROUND(AVG(ZUTAT.KALORIEN),2)
                AS 'AVG Kalorien',
    ROUND(AVG(ZUTAT.KOHLENHYDRATE),2)
                AS 'AVG Kohlenhydrate',
    ROUND(AVG(ZUTAT.PROTEIN),2)
                AS 'AVGProteine'
    FROM BESTELLUNG
        NATURAL JOIN BESTELLUNGZUTAT
        NATURAL JOIN ZUTAT
        NATURAL JOIN KUNDE
WHERE KUNDENNR=2001;